### ISSUE TITLE
Canvas sized incorrectly on iOS when VR display is deactivated

### ISSUE THREAD

**Issue by bcdarius** [videojs/videojs-vr#103]
## Description
When deactivating VR display on iOS, the rendered canvas is not restored its original size.

## Steps to reproduce
1. Load the player in landscape mode on iOS device - [example test case](https://cs1.brightcodes.net/doleskevicius/tests/videojs-vr/)
2. Tap play 
3. Once the content starts playing click on the cardboard button in control bar to activate VR display
4. Tap on the cardboard button again to toggle off VR display 

### Expected
When VR display is deactivated the display is sized to match the player size.

### Actual 
The rendered canvas is set to 101x100px once VR is deactivated making content appear as a small square at the top left corner of the player.

### versions
1.4.0
#### videojs
6.x/7.x
#### browsers
Safari
#### OSes
iOS 11.x

**Comment by BrandonOCasey** [comment]
Fixed in #104
