### ISSUE TITLE
Update camera rotation

### ISSUE THREAD

**Issue by xMADOXX** [videojs/videojs-vr#105]
Hi,

I'm trying to update the camera rotation. I've tried things like this :
- player.vr().camera.rotation.x = 100
- player.vr().camera.rotation.y = 100
- player.vr().camera.rotation.z = 100

Nothing is working but I'm able to move the position of the camera but I really want to change the rotation.

I've found this way to rotate the camera : 
- this.player().vr().controls3d.orbit.rotateLeft(...)
- this.player().vr().controls3d.orbit.rotateUp(...)

But how can I turn it smoothly with library like TweenJs ?
Any ideas ?

**Comment by xMADOXX** [comment]
Perfect, thank you @BrandonOCasey

**Comment by BrandonOCasey** [comment]
No problem @xMADOXX. Feel free to open another issue if you have any more trouble.

**Comment by JuanIrache** [comment]
Is there a way to rotate around the front-back axis?

**Comment by jkirkcaldy** [comment]
> Is there a way to rotate around the front-back axis?

Did you ever figure this out?

**Comment by JuanIrache** [comment]
Kind of. Given a desired rotation of 0, 90, 180, 270, or 360:

```
const { scene } = player.vr()
const HALF_PI = Math.PI / 2
const radians = (rotation * Math.PI) / 180
switch (rotation) {
  case 90:
    scene.children[0].rotation.set(-HALF_PI, 0, -radians)
    break
  case 180:
    scene.children[0].rotation.set(0, HALF_PI, -radians)
    break
  case 270:
    scene.children[0].rotation.set(HALF_PI, 0, -radians)
    break
  default:
    scene.children[0].rotation.set(0, -HALF_PI, -radians)
    break
}
```

I'm not sure if this works for all use cases.
