### ISSUE TITLE
"module" field in package is not transpiled

### ISSUE THREAD

**Issue by ferdaber** [videojs/videojs-vr#116]
## Description
I am using videojs-vr with webpack and allowing webpack to resolve imports of this package to its module field, however I have also disabled all Babel transpilation for anything inside my node_modules directory (I believe this is the most common configuration for most webpack users).

This causes a problem with videojs-vr being loaded in IE11 as it doesn't support the ES6 class syntax. The `"module"` field in `package.json` points to an untranspiled `videojs-vr.es.js` file.

I'm aware that there's barely any consensus as to what should actually be put into the `"module"` field in `package.json`, (is it modern JS? or transpiled JS with ES6 import/export to allow tree-shaking?) so I'm opening issue just to raise awareness. If the maintainers are okay with keeping modern JS in the `"module"` field then go ahead and close the issue; if you want to change this, I'd gladly open a PR to change this.

The current workaround I'm using is to set an alias in my `webpack.config.js` to point to `videojs-vr.cjs.js` instead, which does transpile away the ES6 class syntax.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Set up webpack without any plugins (default configuration)
2. Import videojs-vr in the main entry file
3. Run the bundler
4. Open the page in IE11

### Expected
The page loads (whether or not videojs-vr is actually actively being used in that page)

### Actual
A syntax error is thrown

**Comment by gkatsev** [comment]
Thanks for opening the issue, we're aware and we have a fix pending release in the generator https://github.com/videojs/generator-videojs-plugin/pull/196. In the mean time, I would downgrade to the 1.4.1

**Comment by ferdaber** [comment]
Ah, wonderful - thanks for the super quick response!
