### ISSUE TITLE
VR Plugin and associated event handlers are not disposed correctly

### ISSUE THREAD

**Issue by ferdaber** [videojs/videojs-vr#118]
## Description
I just learned that according to MDN, when adding an event listener under the capturing phase, removing that event listener must also be under the capturing phase, what this means is that the browser tracks event listeners under the capturing phase separately than listeners under the bubbling phase:
```js
window.addEventListener('resize', myFunc, true)
window.removeEventListener('resize', myFunc, true) // <- true has to be passed in as 3rd arg, otherwise it won't work
```
In the following code in the plugin, that is not being followed and unfortunately those event listeners are staying around after the player is disposed. This is causing issues in my team's code as the player tries to access elements that are no longer there (and in general is a memory leak)
https://github.com/videojs/videojs-vr/blob/faa7d9ac7ee89899aa6abe8eae9018b0da0703d1/src/plugin.js#L514
https://github.com/videojs/videojs-vr/blob/faa7d9ac7ee89899aa6abe8eae9018b0da0703d1/src/plugin.js#L548

My current workaround is to just monkey-patch the `reset` method:
```js
const VR = window.videojs && window.videojs.getPlugin('vr')
if (VR) {
    const oldReset = VR.prototype.reset
    VR.prototype.reset = function reset() {
        oldReset.apply(this, arguments)
        window.removeEventListener('resize', this.handleResize_, true)
        window.removeEventListener('vrdisplaypresentchange', this.handleResize_, true)
        window.removeEventListener('vrdisplayactivate', this.handleVrDisplayActivate_, true)
        window.removeEventListener('vrdisplaydeactivate', this.handleVrDisplayDeactivate_, true)
    }
}
```

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Initialize a video player with VR capabilities
2. Dispose that video player
3. Resize that window

### Expected
No errors

### Actual
A console error is logged as the old listener tries to access a video element that is no longer there
![image](https://user-images.githubusercontent.com/12239873/43472680-b35f9c8c-94b3-11e8-9533-6b17e7f36e66.png)

#### videojs
what version of videojs does this occur with? v6.11.0

#### browsers
what browser are affected? all browsers

#### OSes
what platforms (operating systems and devices) are affected? all platforms

**Comment by BrandonOCasey** [comment]
Should be fixed as of 1.4.4. See #119. Thanks for the report @ferdaber. Feel free to open a PR next time you already had most of the code 👍
