### ISSUE TITLE
create an option from config to disable motion sensor in android devide for display movement

### ISSUE THREAD

**Issue by dioramayuanito** [videojs/videojs-vr#127]
Hello guys!
i just wanna say : thanks a lot for this great plugin ! 👍 
after some experiment in http://flowplugs.detik.com/detikVideo/test/indexvr.php
sometime in android device (Opera and Chrome browsers), video display will be shaking because of motion sensor. I want to disable motion sensor usage, and make movement control by touching the display only.
How to achieve those things?

**Comment by BrandonOCasey** [comment]
This should be fixed when #137 gets merged and released. The option should be called `motionControls`

**Comment by dioramayuanito** [comment]
thanks @BrandonOCasey , you're Awesome 👍

**Comment by BrandonOCasey** [comment]
Should be out in 1.5.0

**Comment by mrkos67** [comment]
question: this seems to enable/disable motionControls during initialization; how would I toggle motionControls off and on in real time without the screwiness that i've discovered and outlined below? 

I've tried:
`vjs.vr().controls3d.orientation.enabled = true/false`
and
`vjs.vr().controls3d.orientation.connect()/disconnect()`
but once I do that, the FOV goes straight up or straight down and spins around spastically, as seen here: https://dev.option5.net/CNCT/Megaphone/master/tests/gyro/
