### ISSUE TITLE
No support for vive, due to issues with webvr-polyfill

### ISSUE THREAD

**Issue by gkatsev** [videojs/videojs-vr#14]
At least in Firefox 55 on windows 10 with HTC Vive, the VRDisplay is rejected because it isn't an instance of a specified type: https://github.com/MetaCDN/webvr-boilerplate/blob/master/src/webvr-manager.js#L136-L144

**Comment by jbroberg** [comment]
Working here (FF 55.0 64 Bit, Vive, Windows 10) on
https://github.com/MetaCDN/videojs-vr
https://videojs-vr.s3.amazonaws.com/latest/example.html

I've only given it a cursory look but hardware/cardboard VR support is pretty wonky in the current state of this (vjs/videojs-vr) repo. It would be good to have something like this for this repo to be checked off for releases:
https://github.com/MetaCDN/videojs-vr/wiki/Browser-Compatibility

**Comment by gkatsev** [comment]
@jbroberg Looks like your example behaves the same way that I saw. I'd have expected to see a cardboard/vr button and then have the video take over the entire viewing area. What I currently see is that if I tell the vive to show the desktop, I can then see the video in the window but it does track the headset. So, maybe it's just an expectation problem.

**Comment by jbroberg** [comment]
@gkatsev - weird. It's working great for me. Is your SteamVR set up correctly? Are you running the 64-Bit version of Firefox 55?

https://videojs-vr.s3.amazonaws.com/latest/example.html

**Comment by gkatsev** [comment]
So, @BrandonOCasey found this matching issue which is the root cause: https://github.com/borismus/webvr-boilerplate/issues/170
https://github.com/googlevr/webvr-polyfill/blob/5f8693a9053ee1dea425e96d14cd1f2bef7a284c/src/webvr-polyfill.js#L39-L40

Basically, `enablePolyfill` runs when it shouldn't. Happened due to this commit: https://github.com/googlevr/webvr-polyfill/commit/1bf23ee1ce5f0a58b17bff8bdff92eddc0d40b2e

If we pin to webvr-polyfill 0.9.23 we should be OK for now. I'll also update the issues and maybe look into a PR to fix it upstream.

**Comment by gkatsev** [comment]
Made a PR against the polyfill: https://github.com/googlevr/webvr-polyfill/pull/276

**Comment by BrandonOCasey** [comment]
We will have to revert #21 when this is fixed

**Comment by gkatsev** [comment]
My PR was merged into the webvr-polyfill, hopefully we'll be able to update once it gets released.

**Comment by jbroberg** [comment]
See https://github.com/videojs/videojs-vr/pull/35 for fix.
