### ISSUE TITLE
Switching Video Sources between 360 and non 360 and back results in projection not occurring.

### ISSUE THREAD

**Issue by AndrewStobie** [videojs/videojs-vr#142]
## Description
Changing between sources that are 360 projections and NONE projections and then back to 360 loads the 360 in the last step as NONE projection with no interactivity

## Steps to reproduce

1. Load a video with mediainfo.projection = '360' and vr({projection: 'AUTO'});
2. Load a video with mediainfo.projection = 'NONE' and vr({projection: 'AUTO'});
3. load again the first video setting mediainfo.projection = '360' and vr({projection: 'AUTO'});

### Expected
To see the same 360 projection on the 360 video

### Actual
the flat non-projected equirectangular video with no tranformation

### Error output
None specific to this issue

## Additional Information
Please include any additional information necessary here. Including the following:

#### videojs
what version of videojs does this occur with? 7.2.2 with http-streaming and videojs-vr 1.5.0

#### browsers
what browser are affected?
chrome on mac, chrome on android pie, safari on mac, safari on iOS, haven't tested FF yet

#### OSes
what platforms (operating systems and devices) are affected?
Mac OS Mojave, iOS12, Android Pie at minimum

### plugins
are any videojs plugins being used on the page? If so, please list them below.
videojs-vr 1.5.0

**Comment by AndrewStobie** [comment]
I'm writing a comment that so far using the player.vr().changeProjection_() method is solving my problem. just thought that should be documented.

**Comment by AndrewStobie** [comment]
Updated update. doing so resulting in an error on load for this.scene or THREE.map being undefined so it's back to the drawing board.

**Comment by BrandonOCasey** [comment]
Interesting, Do you have a test page we could look at?

**Comment by AndrewStobie** [comment]
@BrandonOCasey I apologize that I don't have more information but I did solve this issue. I am using the source for this plugin but I have made a few changes to work it with our needs for react and code splitting. I can try to figure out what it is I did and if it helps, but I am going to close this for now

**Comment by funkmeisterb** [comment]
Here is some code to reproduce the issue. Observed in Windows 10 Chrome. videojs-vr.min.js is 1.5.0.
The MP4 files are Big Buck Bunny and any 360 video.
Repro steps:
- Click on PLAY VR -> OK
- Click on PLAY 2D -> OK
- Click on PLAY VR -> shows up as 2D

```
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Video.js DEMO</title>
    <link href="//vjs.zencdn.net/7.0/video-js.min.css" rel="stylesheet">
    <script src="//vjs.zencdn.net/7.0/video.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="videojs-vr/videojs-vr.min.js"></script>
    <script>
    $(document).ready(function(){
        $("#btn-vr").click(function(){
            console.log("LOAD VR!");
            var player = window.player = videojs('test-videojs');
            player.src({ src: 'vr.mp4' });
            player.mediainfo = player.mediainfo || {};
            player.mediainfo.projection = '360';
            player.vr({projection: 'AUTO', debug: true, forceCardboard: false});
            player.play();
        });
        $("#btn-2d").click(function(){
            console.log("LOAD 2D!");
            var player = window.player = videojs('test-videojs');
            player.src({ src: 'BigBuckBunny.mp4' });
            player.mediainfo = player.mediainfo || {};
            player.mediainfo.projection = 'NONE';
            player.vr({projection: 'AUTO', debug: true, forceCardboard: false});
            player.play();
        });
    });
    </script>

</head>
<body>
    <video id="test-videojs" class="video-js" controls preload="none" width="640" height="264" data-setup="{}">
        <source src="BigBuckBunny.mp4" type="video/mp4">
        <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="//videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
    </video>

    <button id='btn-2d'>PLAY 2D</button>
    <button id='btn-vr'>PLAY VR</button>
</body>

</html>
```

**Comment by funkmeisterb** [comment]
Here is a quick fix:

```
    <script>
    $(document).ready(function(){
        $("#btn-vr").click(function(){
            console.log("LOAD VR!");
            var player = videojs('test-videojs');
            player.src({ src: 'vr.mp4' });
            player.mediainfo = player.mediainfo || {};
            player.mediainfo.projection = '360';
            player.vr({projection: 'AUTO', debug: false, forceCardboard: false});
            player.play();
            try {
                player.vr().changeProjection_("Sphere");
            }
            catch(err) {
                console.log("Error caught!");
            }
        });
        $("#btn-2d").click(function(){
            console.log("LOAD 2D!");
            var player = videojs('test-videojs');
            player.src({ src: 'BigBuckBunny.mp4' });
            player.mediainfo = player.mediainfo || {};
            player.mediainfo.projection = 'NONE';
            player.vr({projection: 'AUTO', debug: false, forceCardboard: false});
            player.play();
        });
    });
    </script>
```
