### ISSUE TITLE
Implement our own webvr-manager 

### ISSUE THREAD

**Issue by BrandonOCasey** [videojs/videojs-vr#18]
Don't use the one from webvr-boilerplate

**Comment by jbroberg** [comment]
I think this is ultimately a good idea. webvr-boilerplate is pretty old/unmaintained at this point. webvr-boilerplate combined with newer/latest webvr-polyfill versions breaks things pretty badly.

I took a very good look at webvr-ui (https://github.com/googlevr/webvr-ui - which is a successor and contains the manager and a new UI pattern) and considered moving to it but found the behaviour to be even worse.
