### ISSUE TITLE
Distribution folder is missing css file

### ISSUE THREAD

**Issue by luiscerqueira** [videojs/videojs-vr#187]
## Description
 [NPM published 1.6.0](https://www.npmjs.com/package/videojs-vr/v/1.6.0) version is missing the  videojs-vr.css file.

## Steps to reproduce
1. npm install videojs-vr@1.6.0
2. try to import the videojs-vr.css

### Expected
CSS file is loaded and the big play button has the correct VR style.

### Actual
CSS file is not loaded because its missing.

### Error output
Error: Can't resolve 'videojs-vr/dist/videojs-vr.css'

## Additional Information
prepublishOnly script may have not run all build scripts

### versions
videojs-vr@1.6.0

**Comment by brandonocasey** [comment]
Sorry for the trouble, this is fixed in 1.6.1
