### ISSUE TITLE
how to use in vuejs?

### ISSUE THREAD

**Issue by pmsmasoud** [videojs/videojs-vr#208]
how to use videojs-vr in vue js project ?
Please explain with an example.

**Comment by Brandonza** [comment]
Hi

Have you found a way to do this? I think something similar to [this](https://github.com/surmon-china/vue-video-player/issues/139#issuecomment-446391135) needs to be done.

**Comment by gkatsev** [comment]
You can follow the sample of using Video.js in vue from out docs site: https://docs.videojs.com/tutorial-vue.html
Then you would include videojs-vr in there as well.
Add an `import 'videojs-vr'` line under the `import videojs from 'video.js'` line.
