### ISSUE TITLE
Videojs 360 Video works on desktop but not mobile

### ISSUE THREAD

**Issue by RaviJayagopal** [videojs/videojs-vr#215]
It works on browser (Windows; Chrome, Firefox & Opera all work fine on desktop).

Does not work on iPhone 7 Plus. Get the following error:

"The media playback was aborted due to a corruption problem or because the media used features your browser did not support."

Here's the link to test: https://www.webmasterinabox.net/browse-button-test-56/

**Comment by decodedmrq** [comment]
+1 same issue

**Comment by RaviJayagopal** [comment]
Resolved.
