### ISSUE TITLE
Uncaught TypeError: player.vr is not a function

### ISSUE THREAD

**Issue by ChenJanson** [videojs/videojs-vr#223]
I use electron with react. And get  Uncaught TypeError: player.vr is not a function.Anyone who solve it please help
    
componentDidMount() {
        // instantiate Video.js
        this.player = videojs(this.videoNode, {
            sources: [{
                type: "video/mp4",
                src: "/video/silk.mp4",
            }],
            preload: "auto",
            // controls: true,
            autoplay: true,
            fluid: true,
        }, function onPlayerReady() {
            console.log('onPlayerReady', this)
            const player = this
            player.mediainfo = player.mediainfo || {}
            player.mediainfo.projection = '360'
            player.vr({
                projection: 'AUTO',
                debug: true,
                forceCardboard: false
            })
        });
    }

VrPlayer.jsx:29 Uncaught TypeError: player.vr is not a function
    at l.onPlayerReady (VrPlayer.jsx:29)
    at l.<anonymous> (video.min.js:12)
    at Array.forEach (<anonymous>)
    at l.<anonymous> (video.min.js:12)
    at video.min.js:12

**Comment by ChenJanson** [comment]
use the newest edition solve the problem

**Comment by naren0021** [comment]
@ChenJanson can you let me know in which version this issue is resolved

**Comment by aaronpk** [comment]
I just installed 1.8.0 and am also getting this error
