### ISSUE TITLE
how to set camera distance 

### ISSUE THREAD

**Issue by yaozhufang-rits** [videojs/videojs-vr#237]
## Description
now the default camera distance is 0. My 360 video looks fuzzy.
I want to extend the distance of the camera and improve the view quality

### Expected
extend the camera distance  and improve the view quality

#### videojs
videojs-vr @Version 1.7.2
video.js 7.11.4

#### browsers
safari, chrome on iPhone iOS 14

#### OSes
iPhone iOS 14

**Comment by yaozhufang-rits** [comment]
try to set the fov & zoom value as below, i can extend the distance of the camera.

this.fov = fov !== undefined ? fov : 80;
this.zoom = 0.5

**Comment by tsuk29** [comment]
FYI

if you need to set the above, call them in initialized event or get the following error.

`TypeError: Cannot set properties of undefined (setting 'zoom')`

```ts
      const vrPlayer = player.value.vr({
        projection: '360',
      });
      vrPlayer.on('initialized', () => {
       // you can access camera property in this block.
        vrPlayer.camera.zoom = 0.8;
        vrPlayer.camera.fov = 80;
      });
```
