### ISSUE TITLE
Depends on vulnerable versions of three

### ISSUE THREAD

**Issue by RoopanV** [videojs/videojs-vr#244]
npm audit gives below error

three  <0.125.0
Severity: high
Regular Expression Denial of Service - https://npmjs.com/advisories/1639
No fix available
node_modules/three
  videojs-vr  *
  Depends on vulnerable versions of three
  node_modules/videojs-vr

version installed  "videojs-vr": "^1.8.0",

**Comment by gkatsev** [comment]
I've published this as 1.10.0. It's tagged `next` on npm. Please try it out and let me know if there are issues, thanks.

**Comment by andreas-venturini** [comment]
It works for us, just noticed these warnings in the console

![image](https://user-images.githubusercontent.com/4801917/133797384-3ba5d0d0-1133-4819-be3d-483e3a7095be.png)
