### ISSUE TITLE
What is the actual code license?

### ISSUE THREAD

**Issue by SamantazFox** [videojs/videojs-vr#264]
- [LICENSE](https://github.com/videojs/videojs-vr/blob/main/LICENSE) is MIT (a.k.a Expat)
- [package.json](https://github.com/videojs/videojs-vr/blob/eb80c8a55909be14a80ae93dfa295b7266f5aff4/package.json#L23) says Apache 2.0

what is the correct license for this repo ?

**Comment by gkatsev** [comment]
Looks like the package.json field got changed in an update based on our plugin generator. Given that MIT is the original license and the Apacha 2.0 change was likely not intended, we're going to keep this repo as MIT.

We'll make sure to make a PR to update it.

**Comment by gkatsev** [comment]
Fix is published as 1.10.1
