### ISSUE TITLE
Fix/Finish 360 Cubemap implementation

### ISSUE THREAD

**Issue by jbroberg** [videojs/videojs-vr#34]
There is a partial (broken) cubemap implementation that is incomplete. The aim is to play back 360 video in the cubemap, such as generated by Facebook:

https://code.facebook.com/posts/1638767863078802/under-the-hood-building-360-video/
https://github.com/facebook/transform360

**Comment by BrandonOCasey** [comment]
See #86

**Comment by BrandonOCasey** [comment]
This is now supported as of 1.3.0!
