### ISSUE TITLE
Problem with HLS on iOS

### ISSUE THREAD

**Issue by gen4sp** [videojs/videojs-vr#37]
I am trying to play 5 sec TopToBottom video and it works well on desktop browsers. But on iOS safari, it just shows spinner and black screen for about 5 minutes and load CPU up to 100%.
There are no any errors in console.

This is possible to use this plugin with videojs-contrib-hls.js ?

**Comment by jbroberg** [comment]
Hi @gen4sp 

Do you have an example page somewhere we can look at?

Also - the m3u8, all segments and the player page need to be served from the same domain due to CORs limitation on Safari.

**Comment by gen4sp** [comment]
first approximation, but with another Video (while I am waiting for allowance to share our one)
http://jsbin.com/wegejereji

It works better on desktop, but doesn't at all on safari mobile

**Expected:**
- Video buffered as far as page loaded and paused.
- The video will be with 2 barrels view for cardboard.

**Now on Safari on my IPhone:**
- Video is not buffered after page load
- After tap, video loads too long or never started (after 2-3 minutes of spinner it shows: your browser  doesn't support some features)
- No barrels view for cardboard, just plain video

**Comment by jbroberg** [comment]
Hi there

As mentioned the HLS and page need to be loaded from the same domain due to Safari defect. This will never work otherwise. See these links for some background:
https://github.com/MetaCDN/videojs-vr/issues/5
https://github.com/MetaCDN/videojs-vr/issues/20

Try these links on your iPhone:
https://videojs-vr.s3.amazonaws.com/latest/example-local.html
https://videojs-vr.s3.amazonaws.com/latest/example-local-hls.html

**Comment by gen4sp** [comment]
Yes, but it works the same way as locally, and locally I experience the same behavior.

**Comment by jbroberg** [comment]
Do the above links for for you?

Please share an example page where the page, playlist and segments are all loaded from the same page and we can go from there.

**Comment by gen4sp** [comment]
yes, sure
http://gwsp.s3-website-eu-west-1.amazonaws.com/ 
- does not work preload
- loading (after tapin' "GO") is quite long sometimes. 
- accelerometer control seems doesn't work? I can see the video on mobile.

**Comment by BrandonOCasey** [comment]
Sorry for taking so long to respond, we just had a new release (1.1.0). That should fix a lot of issues with HLS on safari and iOS

**Comment by BrandonOCasey** [comment]
Feel free to re-open if this is still an issue
