### ISSUE TITLE
Uncaught TypeError: e.getPlugin is not a function

### ISSUE THREAD

**Issue by DanielnetoDotCom** [videojs/videojs-vr#38]
What that should be?
I am including Video.js 5.20.0 before videojs-vr
I am including the min.js version
any idea?

![image](https://user-images.githubusercontent.com/18009293/32104712-fffb6f04-bafb-11e7-9052-a812cfde5fef.png)

**Comment by DanielnetoDotCom** [comment]
Never mind, I update to video.js 6 and it works, but now I am having a warning 

`VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead`

**Comment by BrandonOCasey** [comment]
Should be fixed in the most recent version, re-open if you are still having issues!
