### ISSUE TITLE
Any Idea why my video is all black?

### ISSUE THREAD

**Issue by DanielnetoDotCom** [videojs/videojs-vr#39]
Some one had this problem before? the 360 logo appear, but the video when I play is all black

**Comment by DanielnetoDotCom** [comment]
I dettect, we can not try to ser aspect ration on it. I have removed it and it is working

**Comment by nvybvl** [comment]
Yea, I think you have problems with cross domain

**Comment by BrandonOCasey** [comment]
Black video almost always means cross domain issues. With version 1.1.0 we have an error for this issue now. See #40 to discuss

**Comment by nvybvl** [comment]
try to put on video tag .  crossdomain="anonymous"
https://stackoverflow.com/a/41831848/8342662
