### ISSUE TITLE
Click and drag not working on Firefox 57

### ISSUE THREAD

**Issue by Aauslander920** [videojs/videojs-vr#42]
Hello,

Thank you for this wonderful plugin! Everything works nicely on Chrome and on older versions of Firefox; however, on Firefox 57, we can't click and drag to pan around our 360 stream even though the stream plays. We're getting this error in the console:

TypeError: hmd is null
videojs-vr.js:49450:30

It appears that the plugin isn't fully instantiated on our Videojs instance; Firefox seems not to recognize any VR displays. Please let me know if there is a workaround or fix.

Thanks!

**Comment by jbroberg** [comment]
Hi there,

Do you have a HMD connected at all (either Rift or Vive)?

cheers

James

**Comment by jbroberg** [comment]
@BrandonOCasey is this related?
https://github.com/videojs/videojs-vr/commit/76e6e036f65067bb5f4c291f65ad3173c51dfdda

@Aauslander920 are you using the latest release (1.0.3)?

**Comment by Aauslander920** [comment]
@jbroberg Thanks for the quick response! No, nothing fancy - we don't have any HMD connected. Just trying to display some 360-degree video in 1 of our 4 VideoJS instances. And yes, we are using the latest release.

**Comment by Aauslander920** [comment]
Hi @jbroberg and @BrandonOCasey, do you have any update on this issue? Please let me know.
Thank you!
Abi

**Comment by BrandonOCasey** [comment]
Seems like windows 57 got native webvr support and that broke the controls, I have a fix
