### ISSUE TITLE
webpack compile error on version 1.1.0

### ISSUE THREAD

**Issue by developpeur2000** [videojs/videojs-vr#50]
Hello,
Since version 1.1.0, the module generates warnings and will corrupt the resulting build in my environment (vue-loader/webpack)
to reproduce : 
- clone the vuejs webpack template at https://github.com/vuejs-templates/webpack
- follow instructions from the readme to generate a simple project, choose minimum features
- in the generated project directory, check `npm run dev` generates no issue
- `npm install videojs-vr@1.1.0`
- edit src/App.vue and add `import 'videojs-vr'` juste before the `import HelloWorld ...`
- npm run dev will generate lots of warnings ( export 'default' (imported as 'THREE__default') was not found in 'three' ) and will get the dev server start to be stuck

version 1.0.3 is fine, it obviously comes from commit https://github.com/videojs/videojs-vr/commit/a5cf671e55feb3c86d2c33489574d20dd37c321a but i'm not a webpack expert enough to find exactly where this comes from

**Comment by BrandonOCasey** [comment]
I am pretty sure this is due to us removing the `three` example code from our repo and including it from the examples folder in the node module. The problem was that the example code isn't exposed as modules so its rather hard to work with. We decided to do a find-replace on the files as they get imported so that they would be exported as regular modules. See https://github.com/videojs/videojs-vr/blob/a5cf671e55feb3c86d2c33489574d20dd37c321a/scripts/rollup-replace.js#L8-L11

**Comment by gkatsev** [comment]
Maybe we need to pre-compile threejs into this project on publish so that users don't need to do anything?

**Comment by BrandonOCasey** [comment]
yeah maybe into the cjs and es modules

**Comment by developpeur2000** [comment]
Hi and thanks for the fast replies,
I confirm that the problem comes from the three example code
The issue is that the replacement code `THREE = require('three')` is compiled as `import THREE__default from 'three';` in the es module
By removing `var THREE = require('three');` from the replacement, and using rollup-plugin-inject to expose THREE to the examples, this seems to work

See my commit on my fork : https://github.com/developpeur2000/videojs-vr/commit/59dc291922fa3f3d2571b9c603e0fb9a77835550

**Comment by BrandonOCasey** [comment]
If you have a chance can you try: https://github.com/videojs/videojs-vr/pull/53 I think that may fix webpack. I tested it and it appears to work, but I have not worked with webpack that much.

**Comment by developpeur2000** [comment]
I've left you a comment on the PR because i could not compile videojs-vr without a small change, but once compiled, it fixes the webpack issue 👍

**Comment by BrandonOCasey** [comment]
OK I made the fix and merged it into master, going to cut a patch release

**Comment by BrandonOCasey** [comment]
1.1.1 is out with the fixes, feel free to re-open if its not working. Thanks for reporting, testing, and helping with this issue!
