### ISSUE TITLE
Your browser/device does not support HLS 360 video

### ISSUE THREAD

**Issue by nvybvl** [videojs/videojs-vr#59]
Hi devs,

My plan is to make HolaPlayer works with VideoJs-Vr plugin but I know I miss something and I want to share with you a part of my code.

1. First of all, you can see VideoJs & VideoJs-vr working together here: https://jsfiddle.net/nvybvl/6hffdf8c/10/
- You'll see the error from the issue title.

2. Second, you can see HolaPlayer (which is an extension of videojs. videojs on steroids as they say)
with VideoJS-Vr here: https://jsfiddle.net/nvybvl/6hffdf8c/16/

Both of them isn't working.
I miss something ?
Thanks

**Comment by mgara** [comment]
Maybe cause your videojs vr file is hosted in some weird 'cdn'

**Comment by youssinsa** [comment]
Hi ! Any news about the "Your browser/device does not support HLS 360 video" issue ? 

Thanks a lot

**Comment by BrandonOCasey** [comment]
This usually happens do to `crossorigin` not being set to `anonymous` on the video element. What browsers are you seeing this on? Currently we had to drop support for iOS10 as it has CORS related issues with HLS video on the WebGL video texture.

**Comment by BrandonOCasey** [comment]
If this is still an issue for anyone, feel free to re-open. Please note though that we only support the latest browsers on each platform as the spec for WebVR is constantly changing and our underlying polyfill only supports the lastest browsers. This issue seems related to crossorigin issues on iOS < 11

**Comment by nickkraakman** [comment]
I am actually experiencing the exact same thing on Chrome 70 on MacOS Mojave.

**Comment by shivarajnaidu** [comment]
As @brandonocasey  told setting **crossorigin** to **anonymous** works.. but what is the issue and why it requires crossorigin .. any idea guys ?

**Comment by ffTsuzuku** [comment]
@shivarajnaidu Hey did you ever figure out why setting crossorigin to anonymous solves this issue?
