### ISSUE TITLE
Responsive Issues

### ISSUE THREAD

**Issue by TwisterMc** [videojs/videojs-vr#72]
Out of the box, videojs-vr doesn't seem to be responsive. So I add in the class of `vjs-16-9` per the videojs documentation and the video becomes responsive, but now 360 videos appears below the video-js div, out of sight. I was just left with a black box.

I've traced this back to the canvas tag being set to `height: inherit; width: inherit` instead of `height: 100%; width: 100%; position:absolute; top:0;`

Hopefully that makes sense as I don't have an example to show right now.

**Comment by BrandonOCasey** [comment]
Can you test #76, I think that should fix this.

**Comment by TwisterMc** [comment]
Looks like it's working for me!
