### ISSUE TITLE
Stuck in Cardboard View on iOS

### ISSUE THREAD

**Issue by TwisterMc** [videojs/videojs-vr#73]
In iOS, if you hit the Cardboard icon, you get a screen that says to place the phone in a Cardboard viewer. I don't have one, so I just want to go back to the video, but I can't. There is no way to exit this view without reloading the page.

![cardboard-issue](https://user-images.githubusercontent.com/46997/39642360-272a7518-4f97-11e8-8dc1-43923e5c68b6.jpeg)

Please add a close button.

**Comment by BrandonOCasey** [comment]
Can you try https://github.com/videojs/videojs-vr/pull/75. That should turn off rotate instructions. From there you will just have to click the cardboard button again to exit.

**Comment by TwisterMc** [comment]
I'll give that a try.

I didn't realize that was rotate instructions. It makes sense now that you say that, but I had no idea that if I rotated my phone on that screen it'd be any different.

**Comment by TwisterMc** [comment]
Unless I'm missing something, that just hides the button right? It'd be nice to keep the button for people that have Cardboard, but also allow people to get out of that view who accidentally tap it.
