### ISSUE TITLE
Mouse/Arrow keys/touch is not working to move 360 videos

### ISSUE THREAD

**Issue by danielgroppo** [videojs/videojs-vr#91]
Hello everyone,

The video can move perfectly using the gyroscope, however when using the touch, mouse or arrow keys, I can not move the video, it is fixed in a single location. The only action that I can do with the mouse/touch is pause.

Does anyone have any idea how to solve this?

Thank you very much!

**Comment by BrandonOCasey** [comment]
Hi!

Touch controls were removed out from under us in the underlying library in a version update. We could not roll back the version because it fixed several issues with Chrome. Their is currently a pr out to re-implement said controls: https://github.com/videojs/videojs-vr/pull/89

**Comment by BrandonOCasey** [comment]
Should be fixed in 1.3.0, feel free to re-open if that isn't the case.
